# Gradle Properties
org.gradle.jvmargs = -Xmx2G

# Runtime
game_memory = 2G

# Mod Info
mod_version = 2.4.10

# Maven Info
maven_group = surreal
archive_name = Bubbles

# We're back transforming some shi- people don't know how to code cuh!
plugin_class = baubles.core.BubblesCore

# Other Mods
actually_additions = false
ae2_ext_table = false
applied_energistics_2 = false
armored_arms = false
# 0 - None | 1 - Official | 2 - RLCraft
artifacts_mod = 0
better_animals_plus = false
botania = false
broken_wings = false
cofh_core = false
cosmetic_armor = false
dark_utilities = false
draconic_evolution = false
electroblobs_wizardry = false
extra_utilities_2 = false
groovyscript = false
improved_backpacks = false
just_enough_items = false
# 0 - None | 1 - Official | 2 - Unofficial
mini_effects = false
# 0 - None | 1 - Official | 2 - Unofficial
mouse_tweaks = 0
nae2 = false
natural_pledge = false
necromancers_delight = false
# 0 - None | 1 - Normal | 2 - Overhauled
nuclearcraft = 0
overloaded_armor_bar = false
quality_tools = false
quark_rotn = false
plethora = false
plustic = false
random_things = false
redstone_repository = false
reliquary = false
simply_backpacks = false
spartan_weaponry = false
super_sound_muffler = false
tetra = false
thaumcraft = false
thaumic_additions = false
thaumic_augmentation = false
thaumic_energistics = false
thaumic_wonders = false
the_one_probe = false
trinkets_and_baubles = false
twilight_forest = false
universal_tweaks = false
wearable_backpacks = false
wings = false
wizardry = false

# * Random Complement
# * RLMixins = Pre 1.4 (1.3.18) [A]
# * Incontrol Continuation [T]
# * Bring Me The Rings [I]
# * Roidtweaker = CraftTweaker support
# * Baubley Elytra [I]
# * Random Tweaker
# * MIA