just_enough_items = false
actually_additions = false
armored_arms = false
better_animals_plus = false
the_one_probe = false
# 0 - None | 1 - Official | 2 - RLCraft
artifacts_mod = 0
cosmetic_armor = false
groovyscript = false
improved_backpacks = false
mini_effects = false
# 0 - None | 1 - Official | 2 - Unofficial
mouse_tweaks = 0
natural_pledge = false
# 0 - None | 1 - Normal | 2 - Overhauled
nuclearcraft = 0
plethora = false
quality_tools = false
spartan_weaponry = false
thaumic_additions = false
thaumic_augmentation = false
universal_tweaks = false
wings = false
trinkets_and_baubles = false
reliquary = false
wizardry = false
botania = false
electroblobs_wizardry = false
thaumcraft = false
cofh_core = false
